### ISSUE TITLE
stat

### ISSUE THREAD

**Issue by Tako-San** [TheRedHotHabanero/3_sem#2]
Program works nice. There is only minor fixes from me
- [x] tabs
      In some line tabs used instead of spaces. Lines: 54, 56, 60, 76, 78, 85, 92, 94
- [x] exits
      You may use `return` instead of `exit` in your all cases
- [x] printfs
      You may write every of this `printf` in one line:
      https://github.com/TheRedHotHabanero/3_sem/blob/cb017a52c1b198da9d7252be3dc05b08710bfcc0/1_stat/main.c#L70-L83

**Comment by TheRedHotHabanero** [comment]
man codestyle so shut up
