### ISSUE TITLE
task 2

### ISSUE THREAD

**Issue by Tako-San** [TheRedHotHabanero/3_sem#3]
- [ ] double write
Looks like you are writing to file twice. First time here:
https://github.com/TheRedHotHabanero/3_sem/blob/cb017a52c1b198da9d7252be3dc05b08710bfcc0/2_open_write_close/2_1.cpp#L40
And second here:
https://github.com/TheRedHotHabanero/3_sem/blob/cb017a52c1b198da9d7252be3dc05b08710bfcc0/2_open_write_close/2_1.cpp#L47
- [x] compilation fail
Can't compile task 2 even with your `CMakeLists.txt`. Error:
```bash
error: invalid conversion from ‘const void*’ to ‘const uint8_t*’ {aka ‘const unsigned char*’} [-fpermissive]
   12 |   const uint8_t *buf_addr = buf;
      |                             ^~~
      |                             |
      |                             const void*
```

**Comment by TheRedHotHabanero** [comment]
compiles now
